# default_language_version:
#   python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--filter-files"
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          # see https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#flake8
          - "--max-line-length=80"
          - "--select=C,E,F,W,B,B950"
          - "--extend-ignore=E203,E501,E704"
        additional_dependencies:
          - flake8-bugbear
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: poetry run -- pytest
        types: [python]
        pass_filenames: false
